blogs/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, CommentCreateView


app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<int:pk>/', BlogDetailView.as_view()  ,name='detail'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('products.urls')),
    path('', include('users.urls')),
    path('blogs/', include('blogs.urls')),
    path('orders/', include('orders.urls')),




]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import HomeView, ContactView, ContactCreateView, wishlist_view, WishlistListView, add_to_cart




app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('wishlist/<int:id>/', wishlist_view, name='wishlist'),
    path('add-cart/<int:id>/', add_to_cart, name='add-cart'),
    path('wishlist-list/', WishlistListView.as_view(), name='wishlist-list'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/create/', ContactCreateView.as_view(), name='contact_create')


]

orders/urls.py
from django.urls import path
from .views import shopping_cart_view, delete_cart_value_view, CheckoutView

app_name = 'orders'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('shopping-cart/', shopping_cart_view, name='shopping-cart'),
    path('delete-cart-value/<int:id>/', delete_cart_value_view, name='delete-cart')
]

products/urls.py
from django.urls import path
from .views import ProductListView

app_name = 'products'

urlpatterns = [

    path('products/', ProductListView.as_view(), name='all')
    
]

users/urls.py
from django.urls import path
from .views import  registration_view, login_view, logout_view, UserProfileView

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),


    path('register/', registration_view, name='register'),

]

blogs/models.py
from django.db import models
from ckeditor.fields import RichTextField
from users.models import UserModel




class BlogTagsModel(models.Model):
    name = models.CharField(max_length=100)



    def __str__(self):
        return self.name
    


    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'






class BlogModel(models.Model):
    title = models.CharField(max_length=200)
    body = RichTextField()
    main_image = models.ImageField(upload_to='blogs/')
    banner_image = models.ImageField(upload_to='blogs/')
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='blogs')
    tags = models.ManyToManyField(BlogTagsModel, related_name='blogs')
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.title
    

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'
        ordering = ('-id',)


class CommentModel(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=13)
    comment = models.TextField()
    blog = models.ForeignKey(BlogModel, on_delete=models.RESTRICT, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    


    def __str__(self):
        return f"{self.name} {self.email}"
    

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
    




    

main/models.py
from django.db import models
from products.models import ProductModel
from users.models import UserModel
from django.db import IntegrityError


class WishListModel(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)


    @staticmethod

    def create_or_delete(user, product):
        try:
            WishListModel.objects.create(user=user, product=product)
        except IntegrityError:
            WishListModel.objects.get(user=user, product=product).delete()    




    def __str__(self):
        return f"{self.user} {self.product}"
    
    class Meta:
        verbose_name = 'wishlist'
        verbose_name_plural = 'wishlists'
        unique_together = ['user', 'product']





class ContactMessageModel(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name


    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'




class BannerModel(models.Model):
    collection = models.CharField(max_length=100)
    title = models.CharField(max_length=150)
    description = models.TextField()
    banner_image = models.ImageField(upload_to='banners')
    status = models.BooleanField(default=True)



    def __str__(self):
        return self.title
    


    class Meta:
        verbose_name = 'banner'
        verbose_name_plural = 'banners'

blogs/forms.py
from django import forms
from .models import CommentModel

class CommentForm(forms.ModelForm):

    class Meta:
        model = CommentModel
        exclude = ['created_at']
        widgets = {
            'name' : forms.TextInput(attrs={'placeholder':"Name"}),
            'email' : forms.EmailInput(attrs={'placeholder':"Email"}),
            'phone' : forms.TextInput(attrs={'placeholder':"Phone"}),
            'comment' : forms.Textarea(attrs={'placeholder':"Comment"}),



        }

    

main/forms.py
from django import forms
from .models import ContactMessageModel




class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessageModel
        exclude = ['created_at']
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Name'
            }),
            'email':forms.EmailInput(attrs={
                'placeholder': 'Email'
            }),
            'message': forms.Textarea(attrs={
                'placeholder': 'Message'
            })

            
        }
   

blogs/views.py
from typing import Any, Dict
from django.db import models
from django.shortcuts import render, redirect,  get_object_or_404, reverse
from .models import BlogModel
from django.views.generic import ListView, DetailView, CreateView
from .forms import CommentForm
from .models import BlogTagsModel








class BlogListView(ListView):
    template_name = 'main/blog.html'
    paginate_by = 6
    

    def get_queryset(self):
        qs = BlogModel.objects.all()
        tag = self.request.GET.get('tag', '')
        if tag:
            qs = qs.filter(tags=tag)
        return qs    


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)    
        tag = self.request.GET.get('tag', '')
        if tag:
            context['tags'] = get_object_or_404(BlogTagsModel, pk=tag)
        return context    





class BlogDetailView(DetailView):
    template_name = 'main/blog-details.html'
    model = BlogModel
    

        

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context
    

class CommentCreateView(CreateView):
    template_name = 'main/blog-details.html'
    form_class = CommentForm


    def form_valid(self, form):
        blog = get_object_or_404(BlogModel, pk=self.kwargs.get('pk'))
        form.instance.blog = blog
        form.instance.save()
        return super().form_valid(form)




    def get_success_url(self):
        return reverse('blogs:detail', kwargs={'pk':self.kwargs.get('pk')})

main/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, reverse, redirect
from django.views.generic import TemplateView, ListView
from .models import BannerModel, WishListModel
from .forms import ContactForm
from django.views.generic import CreateView
from products.models import ProductModel



def add_to_cart(request, id):
    cart = request.session.get('cart', [])
    if id in cart:
        cart.remove(id)
    else:
        cart.append(id)
    request.session['cart'] = cart    
    return redirect(request.GET.get('next', '/'))            



class WishlistListView(ListView):
    template_name = 'main/wishlist.html'

    def get_queryset(self):
        return ProductModel.objects.filter(wishlistmodel__user=self.request.user)

def wishlist_view(request, id):
    product = ProductModel.objects.get(id=id)
    WishListModel.create_or_delete(request.user, product)
    path = request.GET.get('next')
    return redirect(path)

    
class ContactView(TemplateView):
    template_name = 'main/contact.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contact_form'] = ContactForm()
        return context


class ContactCreateView(CreateView):
    form_class = ContactForm
    template_name = 'main/contact.html'

    def get_success_url(self):
        return reverse('main:contact')




class HomeView(TemplateView):

    template_name = 'main/index.html'



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['banners'] = BannerModel.objects.filter(status=True)
        return context

templates/main/index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
    


    <!-- Hero Section Begin -->
    <section class="hero">
        <div class="hero__slider owl-carousel">
            {% for banner in banners %}

            <div class="hero__items set-bg" data-setbg="{{ banner.banner_image.url }}">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-5 col-lg-7 col-md-8">
                            <div class="hero__text">
                                <h6>{{ banner.collection }}</h6>
                                <h2>{{ banner.title }}</h2>
                                <p>{{ banner.description }}</p>
                                <a href="{% url 'products:all' %}" class="primary-btn">Shop now <span class="arrow_right"></span></a>
                                <div class="hero__social">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-pinterest"></i></a>
                                    <a href="#"><i class="fa fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                

            {% endfor %}
           
            
        </div>
    </section>
    <!-- Hero Section End -->

{% endblock  %}    

   

templates/main/shop.html
{% extends 'layouts/base.html' %}
{% load my_tags %}
{% load static %}
{% block content %}



    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shop</h4>
                        <div class="breadcrumb__links">
                            <a href="./index.html">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">

                   {% include 'layouts/shop_sidebar.html' %}

                <div class="col-lg-9">
                    <div class="shop__product__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                               
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__right">
                                    <p>Sort by Price:</p>
                                    <select>
                                        <option value="">Low To High</option>
                                        <option value="">$0 - $55</option>
                                        <option value="">$55 - $100</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    <div class="row">
                        {% for object in object_list %}
                        <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg="{{ object.main_image.url }}">

                                {% if object.is_discount %}
                                    <span class="label">Sale</span>
                                {% endif %}

                                {% if object.is_new %}
                                    <span class="label bg-white text-dark  {% if object.is_discount %}mt-4{% endif %}">New</span>
                                {% endif %}


                                    <ul class="product__hover">
                                        {% if request.user.is_authenticated %}
                                            {% if request.user|is_wishlist:object %}

                                            <li><a href="{% url 'main:wishlist' id=object.id %}?next={{ request.path }}"><img src="{% static 'main/img/heart.png'%}" alt=""></a></li>

                                            {% else %}
                                                
                                            {% endif %}
                                            <li><a href="{% url 'main:wishlist' id=object.id %}?next={{ request.path }}"><img src="{% static 'main/img/icon/heart.png'%}" alt=""></a></li>
                                        {% else %}
                                            <li><a href="{% url 'users:login' %}"><img src="{% static 'main/img/icon/heart.png'%}" alt=""></a></li>
                                        </li>
                                        
                                        {% endif %}
                                       
                                        <li><a href="#"><img src="{% static 'main/img/icon/search.png'%}" alt=""></a></li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6>{{ object.title }}</h6>
                                    {% if object|is_cart:request %}
                                        <a href="{% url 'main:add-cart' id=object.id %}?next={{ request.path }}" class="add-cart" style="color: brown;">- Remove From Cart</a>
                                        
                                    {% else %}
                                        <a href="{% url 'main:add-cart' id=object.id %}?next={{ request.path }}" class="add-cart" style="color: black;">+ Add To Cart</a>
                                    {% endif %}    
                                    <div class="rating">
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    </div>
                                    <h5>${% if object.is_discount %} 
                                         {{ object.real_price }}
                                        <del class="text-secondary">{{ object.price }}</del>
                                    {% else %}
    
                                       {{ object.price }}
                                        
                                    {% endif %}</h5>
                                    <div class="product__color__select">
                                        <label for="pc-4">
                                            <input type="radio" id="pc-4">
                                        </label>
                                        <label class="active black" for="pc-5">
                                            <input type="radio" id="pc-5">
                                        </label>
                                        <label class="grey" for="pc-6">
                                            <input type="radio" id="pc-6">
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                       {% endfor %}
                       
                    </div>


                    {% if page_obj.paginator.count >= 9 %}

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="product__pagination">
                                {% for page in page_obj.paginator.page_range %}
                                     <a class=" {% if page == page_obj.number%}active{% endif %}" href="?page={{ page }}">{{ page }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                        
                    {% endif %}

                   
                </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->
{% endblock %}    

{% block extra_js %}
    <script>
        function addSearchParams(name, value) {
            let searchParams = new URLSearchParams(window.location.search)
            if (searchParams.has(name) && searchParams.get(name) == value) {
                searchParams.delete(name)
            } else {

                searchParams.set(name, value)
            }
            window.location.search = searchParams.toString()
        }

        $(".js-range-slider").ionRangeSlider({
            type: "double",
            grid: true,
            min:{{ min }},
            max:{{ max }},
            from: {% get_current_price request 0 %},
            to: {% get_current_price request 1 %},
            prefix: "$",
            onFinish(data) {
                addSearchParams('price', data.from.toString() + ';' + data.to.toString())
            }
        });




    </script>
{% endblock %}
  

templates/main/shopping-cart.html
{% extends 'layouts/base.html' %}
{% load static my_tags %}
{% block content %}
    


    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shopping Cart</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'main:home' %}">Home</a>
                            <a href="{% url 'products:all' %}">Shop</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shopping Cart Section Begin -->
    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for object in objects  %}
                            
                                <tr>
                                    <td class="product__cart__item">
                                        <div class="product__cart__item__pic">
                                            <img src="{{ object.main_image.url }}" alt="" width="90px" height="90px">
                                        </div>
                                        <div class="product__cart__item__text">
                                            <h6>{{ object.title }}</h6>
                                            <h5>${{ object.real_price }}</h5>
                                        </div>
                                    </td>
                                    <td class="quantity__item">
                                        <div class="quantity">
                                            <div class="pro-qty-2">
                                                <input type="text" value="1">
                                            </div>
                                        </div>
                                    </td>
                                    <td class="cart__price">$ {{ object.real_price }}</td>
                                    <td class="cart__close"><a href="{% url 'orders:delete-cart' id=object.id %}?next={{ request.path }}"><i class="fa fa-close"></i></a></td>
                                </tr>
                            {% endfor %}
                               
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn">
                                <a href="{% url 'products:all' %}" style="color: black;">Continue Shopping</a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn update__btn">
                                <a href="#"><i class="fa fa-spinner"></i> Update cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart__discount">
                        <h6>Discount codes</h6>
                        <form action="#">
                            <input type="text" placeholder="Coupon code">
                            <button type="submit">Apply</button>
                        </form>
                    </div>
                    <div class="cart__total">
                        <h6>Cart total</h6>
                    
                        <ul>
                            {% get_cart_info request as info %}
                            <li>Total <span>$ {{ info.1 }}</span></li>
                        </ul>
                        <a href="{% url 'orders:checkout' %}" class="primary-btn">Proceed to checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shopping Cart Section End -->
{% endblock  %}    

   

templates/main/wishlist.html
{% extends 'layouts/base.html' %}
{% load my_tags %}
{% load static %}
{% block content %}



    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shop</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'main:home' %}">Home</a>
                            <span>Wishlist</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shop__product__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                               
                            </div>
                            <!-- <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__right">
                                    <p>Sort by Price:</p>
                                    <select>
                                        <option value="">Low To High</option>
                                        <option value="">$0 - $55</option>
                                        <option value="">$55 - $100</option>
                                    </select>
                                </div>
                            </div> -->
                        </div>
                    </div>

                    
                    <div class="row">
                        {% for object in object_list %}
                        <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg="{{ object.main_image.url }}">

                                {% if object.is_discount %}
                                    <span class="label">Sale</span>
                                {% endif %}

                                {% if object.is_new %}
                                    <span class="label bg-white text-dark  {% if object.is_discount %}mt-4{% endif %}">New</span>
                                {% endif %}


                                    <ul class="product__hover">
                                        {% if request.user.is_authenticated %}
                                            {% if request.user|is_wishlist:object %}

                                            <li><a href="{% url 'main:wishlist' id=object.id %}?next={{ request.path }}"><img src="{% static 'main/img/heart.png'%}" alt=""></a></li>

                                            {% else %}
                                                
                                            {% endif %}
                                            <li><a href="{% url 'main:wishlist' id=object.id %}?next={{ request.path }}"><img src="{% static 'main/img/icon/heart.png'%}" alt=""></a></li>
                                        {% else %}
                                            <li><a href="{% url 'users:login' %}"><img src="{% static 'main/img/icon/heart.png'%}" alt=""></a></li>
                                        </li>
                                        
                                        {% endif %}
                                       
                                        <li><a href="#"><img src="{% static 'main/img/icon/search.png'%}" alt=""></a></li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6>{{ object.title }}</h6>
                                    {% if object|is_cart:request %}
                                        <a href="{% url 'main:add-cart' id=object.id %}?next={{ request.path }}" class="add-cart" style="color: brown;">- Remove From Cart</a>
                                        
                                    {% else %}
                                        <a href="{% url 'main:add-cart' id=object.id %}?next={{ request.path }}" class="add-cart" style="color: black;">+ Add To Cart</a>
                                    {% endif %}    
                                    <div class="rating">
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    </div>
                                    <h5>${% if object.is_discount %} 
                                         {{ object.real_price }}
                                        <del class="text-secondary">{{ object.price }}</del>
                                    {% else %}
    
                                       {{ object.price }}
                                        
                                    {% endif %}</h5>
                                    <div class="product__color__select">
                                        <label for="pc-4">
                                            <input type="radio" id="pc-4">
                                        </label>
                                        <label class="active black" for="pc-5">
                                            <input type="radio" id="pc-5">
                                        </label>
                                        <label class="grey" for="pc-6">
                                            <input type="radio" id="pc-6">
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                       {% endfor %}
                       
                    </div>


                    {% if page_obj.paginator.count >= 9 %}

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="product__pagination">
                                {% for page in page_obj.paginator.page_range %}
                                     <a class=" {% if page == page_obj.number%}active{% endif %}" href="?page={{ page }}">{{ page }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                        
                    {% endif %}

                   
                </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->
{% endblock %}    

{% block extra_js %}
    <script>
        function addSearchParams(name, value) {
            let searchParams = new URLSearchParams(window.location.search)
            if (searchParams.has(name) && searchParams.get(name) == value) {
                searchParams.delete(name)
            } else {

                searchParams.set(name, value)
            }
            window.location.search = searchParams.toString()
        }



    </script>
{% endblock %}
  