blogs/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, CommentCreateView


app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<int:pk>/', BlogDetailView.as_view()  ,name='detail'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('products.urls')),
    path('', include('users.urls')),
    path('blogs/', include('blogs.urls')),
    path('orders/', include('orders.urls')),




]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import HomeView, ContactView, ContactCreateView, wishlist_view, WishlistListView, add_to_cart




app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('wishlist/<int:id>/', wishlist_view, name='wishlist'),
    path('add-cart/<int:id>/', add_to_cart, name='add-cart'),
    path('wishlist-list/', WishlistListView.as_view(), name='wishlist-list'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/create/', ContactCreateView.as_view(), name='contact_create')


]

orders/urls.py
from django.urls import path
from .views import shopping_cart_view, delete_cart_value_view, CheckoutView

app_name = 'orders'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('shopping-cart/', shopping_cart_view, name='shopping-cart'),
    path('delete-cart-value/<int:id>/', delete_cart_value_view, name='delete-cart')
]

products/urls.py
from django.urls import path
from .views import ProductListView

app_name = 'products'

urlpatterns = [

    path('products/', ProductListView.as_view(), name='all')
    
]

users/urls.py
from django.urls import path
from .views import  registration_view, login_view, logout_view, UserProfileView

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),


    path('register/', registration_view, name='register'),

]

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">


    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/font-awesome.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/elegant-icons.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/magnific-popup.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/nice-select.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/slicknav.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/style.css'%}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>


<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
    <link rel="icon" type="image/png" href="{% static 'main/img/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'main/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'main/fonts/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'main/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
    <link rel="stylesheet" type="text/css" href="{% static 'main/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'main/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/login.css' %}">






</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

   {% include 'layouts/navbar.html' %}

    {% block content %}
        

    
    {% endblock  %}


    {% include 'layouts/footer.html' %}

   
   
    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form" action="{% url 'products:all' %}">
                <input type="text" id="search-input" name="q" value="{{ request.GET.q }}" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->
    <script src="{% static 'main/js/jquery-3.3.1.min.js'%}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>   
    <script src="{% static 'main/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'main/js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'main/js/jquery.nicescroll.min.js'%}"></script>
    <script src="{% static 'main/js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'main/js/jquery.countdown.min.js'%}"></script>
    <script src="{% static 'main/js/jquery.slicknav.js'%}"></script>
    <script src="{% static 'main/js/mixitup.min.js'%}"></script>
    <script src="{% static 'main/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'main/js/main.js'%}"></script>

          	
<!--===============================================================================================-->	
<script src="{% static 'main/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'main/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'main/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'main/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'main/vendor/tilt/tilt.jquery.min.js' %}"></script>
    <script >
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
<!--===============================================================================================-->
    <script src="{% static 'main/js.login.js' %}"></script>



 


    {% block extra_js %}
        
    {% endblock  %}
</body>

</html>

templates/layouts/footer.html
 {% load static %}
 <!-- Footer Section Begin -->
 <footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    
                    <p>The customer is at the heart of our unique business model, which includes design.</p>
                    <a href="#"><img src="{% static 'main/img/payment.png'%}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Clothing Store</a></li>
                        <li><a href="#">Trending Shoes</a></li>
                        <li><a href="#">Accessories</a></li>
                        <li><a href="#">Sale</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Payment Methods</a></li>
                        <li><a href="#">Delivary</a></li>
                        <li><a href="#">Return & Exchanges</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                <div class="footer__widget">
                    <h6>NewLetter</h6>
                    <div class="footer__newslatter">
                        <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                        <form action="#">
                            <input type="text" placeholder="Your email">
                            <button type="submit"><span class="icon_mail_alt"></span></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="footer__copyright__text">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            
                   
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

templates/layouts/login_base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">


    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/font-awesome.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/elegant-icons.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/magnific-popup.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/nice-select.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/slicknav.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/style.css'%}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>


<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
    <link rel="icon" type="image/png" href="{% static 'main/img/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'main/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'main/fonts/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'main/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
    <link rel="stylesheet" type="text/css" href="{% static 'main/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'main/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/login.css' %}">






</head>

<body>
   
    {% block content %}
        

    
    {% endblock  %}


    <!-- Js Plugins -->
    <script src="{% static 'main/js/jquery-3.3.1.min.js'%}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>   
    <script src="{% static 'main/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'main/js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'main/js/jquery.nicescroll.min.js'%}"></script>
    <script src="{% static 'main/js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'main/js/jquery.countdown.min.js'%}"></script>
    <script src="{% static 'main/js/jquery.slicknav.js'%}"></script>
    <script src="{% static 'main/js/mixitup.min.js'%}"></script>
    <script src="{% static 'main/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'main/js/main.js'%}"></script>

          	
<!--===============================================================================================-->	
<script src="{% static 'main/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'main/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'main/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'main/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
    <script src="{% static 'main/vendor/tilt/tilt.jquery.min.js' %}"></script>
    <script >
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
<!--===============================================================================================-->
    <script src="{% static 'main/js.login.js' %}"></script>



 


    {% block extra_js %}
        
    {% endblock  %}
</body>

</html>

templates/layouts/navbar.html
{% load static %}
{% load my_tags %}

<!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__option">
        <div class="offcanvas__links">
            <a href="#">Sign in</a>
           
        </div>
        <div class="offcanvas__top__hover">
            <span>Usd <i class="arrow_carrot-down"></i></span>
            <ul>
                <li>USD</li>
                <li>EUR</li>
                <li>USD</li>
            </ul>
        </div>
    </div>
    <div class="offcanvas__nav__option">
        <a href="#" class="search-switch"><img src="{% static 'main/img/icon/search.png'%}" alt=""></a>
        <a href="#"><img src="{% static 'main/img/icon/heart.png'%}" alt=""></a>
        <a href="#"><img src="{% static 'main/img/icon/cart.png'%}" alt=""> <span>0</span></a>
        <div class="price">$0.00</div>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__text">
       
    </div>
</div>
<!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                      
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            {% if not request.user.is_authenticated %}

                                <a href="{% url 'users:login' %}">Sign in</a>
                                <a href="{% url 'users:register' %}">Sign up</a>

                            {% else %}

                                <a href="{% url 'users:logout' %}">Logout</a>
                                <a href="{% url 'users:profile' %}">Profile</a>


                            {% endif %}
                            

                           
                        </div>
                        <div class="header__top__hover">
                            <span>Usd <i class="arrow_carrot-down"></i></span>
                            <ul>
                                <li>USD</li>
                                <li>EUR</li>
                                <li>USD</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="./index.html"><img src="{% static 'main/img/logo.png'%}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'main:home' %}">Home</a></li>
                        <li><a href="{% url 'products:all' %}">Shop</a></li>
                        <li><a href="#">Pages</a>
                            <ul class="dropdown">
                                <li><a href="./about.html">About Us</a></li>
                                <li><a href="./shop-details.html">Shop Details</a></li>
                                <li><a href="./shopping-cart.html">Shopping Cart</a></li>
                                <li><a href="./checkout.html">Check Out</a></li>
                                <li><a href="./blog-details.html">Blog Details</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'blogs:list'%}">Blog</a></li>
                        <li><a href="{% url 'main:contact'%}">Contacts</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'main:wishlist-list' %}"><img src="{% static 'main/img/icon/heart.png'%}" alt=""></a>
                    {% endif %}
                    {% get_cart_info request as info %}
                    <a href="#" class="search-switch"><img src="{% static 'main/img/icon/search.png'%}" alt=""></a>
                    <a href="{% url 'orders:shopping-cart' %}"><img src="{% static 'main/img/icon/cart.png'%}" alt=""> <span>{{ info.0 }}</span></a>
                    <div class="price">${{ info.1 }}</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->

templates/layouts/shop_sidebar.html
<div class="shop__sidebar">
    <div class="shop__sidebar__search">
        <form action="{% url 'products:all' %}">
            <input type="text" placeholder="Search..." name="q" value="{{ request.GET.q }}">
            <button type="submit"><span class="icon_search"></span></button>
        </form>
    </div>
    <div class="shop__sidebar__accordion">
        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
                </div>
                <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__categories">
                            <ul class="nice-scroll">
                              {% for category in categories %}

                                <li><a onclick="addSearchParams('cat', {{ category.id }})" href="#">{{ category.name }} {{ category.products.count }}</a></li>
                                
                              {% endfor %}
                               
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
                </div>
                <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__tags">
                            <ul>
                                {% for brand in brands %}

                                    <li><a {% if brand.id|stringformat:'i' == request.GET.brand %}
                                        style="color: #000000;"
                                        
                                    {% endif %} onclick="addSearchParams('brand', {{ brand.id }})"  href="#">{{ brand.name }}</a></li>
                                    
                                {% endfor %}
                                
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
                </div>
                <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__price">
                            <input type="text" class="js-range-slider" name="my_range" value=""/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseFour">Size</a>
                </div>
                <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__tags">

                            {% for size in sizes %}

                            <a {% if size.id|stringformat:'i' == request.GET.size %}
                                style="background: #111111; color: #FFFFFF;"
                                
                            {% endif %} onclick="addSearchParams('size', {{ size.id }})" href="#">{{ size.name }}</a>
                                
                            {% endfor %}
                         



                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                    
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
                </div>
                <div id="collapseSix" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__tags">
                            {% for tag in tags %}

                            <a {% if tag.id|stringformat:'i' == request.GET.tag %}
                                style="background: #111111; color: #FFFFFF;"
                                
                            {% endif %} onclick="addSearchParams('tag', {{ tag.id }})" href="#">{{ tag.name }}</a>
                                
                            {% endfor %}
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>